name: tests

on: [push, pull_request]

jobs:
    test:

        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: [7.2, 7.3, 7.4]
                laravel: [6.*, 7.*, 8.*]
                dependency-version: [prefer-lowest, prefer-stable]

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

        steps:
            -   name: Checkout the code
                uses: actions/checkout@v1

            -   name: Disable Xdebug
                run: sudo phpdismod xdebug

            -   name: Install dependencies
                run: composer install --no-progress --no-ansi --profile --no-interaction --no-scripts --no-suggest --prefer-dist

            -   name: Execute tests
                run: vendor/bin/phpunit --testdox --colors=always --exclude-group skipped
